#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := ESP32_SMARTSPRAYER_SLAVE

include $(IDF_PATH)/make/project.mk
